### ISSUE TITLE
Problem with BISC Installation 

### ISSUE THREAD

**Issue by ezgiisenn** [thecailab/BISC#1]
Hello,

First of all, thank you very much for providing this exciting tool.

I have been trying to install BISC in a conda environment (conda v.23.1.0) running under **CentOS Linux 7** on a **x86_64-conda-linux-gnu (64-bit) platform**.  I am contacting you to report some issues I encountered through the installation process. 

As stated in your repository, I installed all stated dependencies (rstan, mgcv, edgeR and splatter) before BISC installation. However, while I was trying to install BISC through GitHub via ```install_github("thecailab/BISC/BISC")```,  I got the following error:

```console
installing *source* package ‘BISC’ ...
** using staged installation
Error in parse(text = lines, srcfile = srcfile(file), keep.source = keep.source) : 
  /tmp/Rtmp4Q1KKZ/R.INSTALL5aaa1addc84e/BISC/R/BISC_differential_bursting.R:23:96: unexpected ')'
22:     kondif=log2(test1[,1:N]/test2[,1:N])
23:     sizedif=log2(test1[,(2*N+1):3*N]/test1[,(N+1):2*N]/(test2[,(2*N+1):3*N])/test2[,(N+1):2*N]))
                                                                                                   ^
Calls: <Anonymous> ... .find_calls_in_file -> .find_calls -> .parse_code_file
Execution halted
ERROR: configuration failed for package ‘BISC’
* removing ‘/home/bq_esen/miniconda3/envs/debug_env/lib/R/library/BISC’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpdNbcx4/file59222b8ed909/BISC_0.0.0.9000.tar.gz’ had non-zero exit status
```

The error seemed to point at an extra paranthesis in line 23 in the source code of ```BISC_differential_bursting.R``` script. To solve the issue, I  downloaded the ```"thecailab/BISC/BISC"``` folder, erased the extra paranthesis in line 23, and manually installed BISC through ```with_libpaths()``` provided by ```withr```. However, after the alteration of the faulty line in the source code of ```BISC_differential_bursting.R``` script, there was still another error causing problem with the installation, this time pointing to another extra paranthesis in line 26: 

```console
Running /home/bq_esen/miniconda3/envs/debug_env/lib/R/bin/R CMD INSTALL \
  /tmp/RtmpCdrrgp/BISC_0.0.0.9000.tar.gz --install-tests 
* installing to library ‘/home/bq_esen/miniconda3/envs/debug_env/lib/R/library’
* installing *source* package ‘BISC’ ...
** using staged installation
Error in parse(text = lines, srcfile = srcfile(file), keep.source = keep.source) : 
  /tmp/RtmplSm3ZW/R.INSTALL6a179a990da/BISC/R/BISC_differential_bursting.R:26:90: unexpected ')'
25:     kondif=test1[,1:N]-test2[,1:N]
26:     sizedif=test1[,(2*N+1):3*N]/test1[,(N+1):2*N]-(test2[,(2*N+1):3*N])/test2[,(N+1):2*N])
                                                                                             ^
Calls: <Anonymous> ... .find_calls_in_file -> .find_calls -> .parse_code_file
Execution halted
ERROR: configuration failed for package ‘BISC’
* removing ‘/home/bq_esen/miniconda3/envs/debug_env/lib/R/library/BISC’
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'R' failed
---
Exit status: 1
stdout & stderr: <printed>
---
```
Finally, when both extra parentheses in the end of line 23 and line 26 were deleted, the source package installation was successfully completed.  I hope this current issue in installation will be resolved for future installations.

Thank you very much in advance.

You can find my sessionInfo() below:
```console
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/bq_esen/miniconda3/envs/debug_env/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] mgcv_1.8-41                 nlme_3.1-162               
 [3] splatter_1.23.1             SingleCellExperiment_1.20.0
 [5] SummarizedExperiment_1.28.0 Biobase_2.58.0             
 [7] GenomicRanges_1.50.2        GenomeInfoDb_1.34.9        
 [9] IRanges_2.32.0              S4Vectors_0.36.1           
[11] BiocGenerics_0.44.0         MatrixGenerics_1.10.0      
[13] matrixStats_0.63.0          rstantools_2.2.0           
[15] rstan_2.21.8                ggplot2_3.4.0              
[17] StanHeaders_2.21.0-7        edgeR_3.40.0               
[19] limma_3.54.0                BISC_0.0.0.9000            
[21] devtools_2.4.5              usethis_2.1.6              
[23] roxygen2_7.2.3              withr_2.5.0                

loaded via a namespace (and not attached):
 [1] bitops_1.0-7           fs_1.6.1               rprojroot_2.0.3       
 [4] backports_1.4.1        tools_4.2.2            profvis_0.3.7         
 [7] utf8_1.2.3             R6_2.5.1               colorspace_2.1-0      
[10] urlchecker_1.0.1       tidyselect_1.2.0       gridExtra_2.3         
[13] prettyunits_1.1.1      processx_3.8.0         compiler_4.2.2        
[16] cli_3.6.0              xml2_1.3.3             desc_1.4.2            
[19] DelayedArray_0.24.0    checkmate_2.1.0        scales_1.2.1          
[22] callr_3.7.3            stringr_1.5.0          digest_0.6.31         
[25] XVector_0.38.0         pkgconfig_2.0.3        htmltools_0.5.4       
[28] sessioninfo_1.2.2      fastmap_1.1.0          htmlwidgets_1.6.1     
[31] rlang_1.0.6            shiny_1.7.4            generics_0.1.3        
[34] BiocParallel_1.32.5    dplyr_1.1.0            inline_0.3.19         
[37] RCurl_1.98-1.10        magrittr_2.0.3         GenomeInfoDbData_1.2.9
[40] loo_2.5.1              Matrix_1.5-3           Rcpp_1.0.10           
[43] munsell_0.5.0          fansi_1.0.4            lifecycle_1.0.3       
[46] stringi_1.7.12         zlibbioc_1.44.0        pkgbuild_1.4.0        
[49] grid_4.2.2             parallel_4.2.2         promises_1.2.0.1      
[52] crayon_1.5.2           miniUI_0.1.1.1         lattice_0.20-45       
[55] splines_4.2.2          locfit_1.5-9.5         knitr_1.42            
[58] ps_1.7.2               pillar_1.8.1           codetools_0.2-19      
[61] pkgload_1.3.2          glue_1.6.2             remotes_2.4.2         
[64] RcppParallel_5.1.6     vctrs_0.5.2            httpuv_1.6.8          
[67] gtable_0.3.1           purrr_1.0.1            cachem_1.0.6          
[70] xfun_0.37              mime_0.12              xtable_1.8-4          
[73] later_1.3.0            tibble_3.1.8           memoise_2.0.1         
[76] ellipsis_0.3.2        

```

**Comment by adamluo12** [comment]
Thanks, the issues were corrected.

**Comment by ezgiisenn** [comment]
Hello again,

First of all, thank you very much for dealing with the issue really fast.

However, despite starting the installation process of BISC from the beggining, I am still having issues with installation now with the respective module loading error:

```console
** R
** inst
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  ‘BISC’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘BISC’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package BISC: Rcpp::loadModule(module = "stan_fit4bhm_mod", what = TRUE, env = ns, : Unable to load module "stan_fit4bhm_mod": Failed to initialize module pointer: Error in FUN(X[[i]], ...): no such symbol _rcpp_module_boot_stan_fit4bhm_mod in package BISC

Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/bq_esen/miniconda3/envs/bisc_proper/lib/R/library/BISC’
Warning message:
In i.p(...) :
 installation of package ‘/tmp/RtmpiyTzpS/file2ee669c492/BISC_0.0.0.9000.tar.gz’ had non-zero exit status
 ```
You can find my sessionInfo() below:

```console
R version 4.2.2 (2022-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/bq_esen/miniconda3/envs/bisc_proper/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] BH_1.81.0-1                 rstantools_2.2.0           
 [3] RcppEigen_0.3.3.9.3         RcppParallel_5.1.6         
 [5] splatter_1.23.1             SingleCellExperiment_1.20.0
 [7] SummarizedExperiment_1.28.0 Biobase_2.58.0             
 [9] GenomicRanges_1.50.2        GenomeInfoDb_1.34.9        
[11] IRanges_2.32.0              S4Vectors_0.36.1           
[13] BiocGenerics_0.44.0         MatrixGenerics_1.10.0      
[15] matrixStats_0.63.0          edgeR_3.40.2               
[17] limma_3.54.1                mgcv_1.8-41                
[19] nlme_3.1-162                Rcpp_1.0.10                
[21] rstan_2.21.8                ggplot2_3.4.1              
[23] StanHeaders_2.21.0-7        devtools_2.4.5             
[25] usethis_2.1.6              

loaded via a namespace (and not attached):
 [1] bitops_1.0-7           fs_1.6.1               rprojroot_2.0.3       
 [4] tools_4.2.2            profvis_0.3.7          backports_1.4.1       
 [7] utf8_1.2.3             R6_2.5.1               colorspace_2.1-0      
[10] urlchecker_1.0.1       withr_2.5.0            gridExtra_2.3         
[13] prettyunits_1.1.1      processx_3.8.0         curl_5.0.0            
[16] compiler_4.2.2         cli_3.6.0              desc_1.4.2            
[19] DelayedArray_0.24.0    scales_1.2.1           checkmate_2.1.0       
[22] callr_3.7.3            stringr_1.5.0          digest_0.6.31         
[25] XVector_0.38.0         pkgconfig_2.0.3        htmltools_0.5.4       
[28] sessioninfo_1.2.2      fastmap_1.1.0          htmlwidgets_1.6.1     
[31] rlang_1.0.6            shiny_1.7.4            BiocParallel_1.32.5   
[34] inline_0.3.19          RCurl_1.98-1.10        magrittr_2.0.3        
[37] GenomeInfoDbData_1.2.9 loo_2.5.1              Matrix_1.5-3          
[40] munsell_0.5.0          fansi_1.0.4            lifecycle_1.0.3       
[43] stringi_1.7.12         zlibbioc_1.44.0        pkgbuild_1.4.0        
[46] grid_4.2.2             parallel_4.2.2         promises_1.2.0.1      
[49] crayon_1.5.2           miniUI_0.1.1.1         lattice_0.20-45       
[52] splines_4.2.2          locfit_1.5-9.7         ps_1.7.2              
[55] pillar_1.8.1           codetools_0.2-19       pkgload_1.3.2         
[58] glue_1.6.2             BiocManager_1.30.19    remotes_2.4.2         
[61] vctrs_0.5.2            httpuv_1.6.8           gtable_0.3.1          
[64] purrr_1.0.1            cachem_1.0.6           mime_0.12             
[67] xtable_1.8-4           later_1.3.0            tibble_3.1.8          
[70] memoise_2.0.1          ellipsis_0.3.2        
>
```
